### ISSUE TITLE
Add ByteItems support

### ISSUE THREAD

**Issue by galoti** [RedNesto/BoxOUtils#1]
Hello!! Could you add support to ByteItems ? ByteItems saves ItemStacks to a database. Several plugins implement ByteItems to have a central database with ItemStack definitions. ByteItems has an API to retrieve ItemStacks:

https://github.com/randombyte-developer/byte-items/blob/20d456db28b90b2436eb30eba19fe02ff1f8afda/src/main/kotlin/de/randombyte/byteitems/ByteItemsApi.kt#L13

https://ore.spongepowered.org/RandomByte/ByteItems

https://github.com/randombyte-developer/byte-items

**Comment by RedNesto** [comment]
Hey, thank you for the suggestion. I need to rewrite some CustomDrops stuff before adding another integration as it is a mess right now, but it should not take too long.

**Comment by galoti** [comment]
Ok, thanks!!

**Comment by RedNesto** [comment]
I just released [v0.7](https://ore.spongepowered.org/RedNesto/Box-O'-Utils/versions/0.7) with ByteItems support.

Again thank you for the suggestion, and for the links (it was way easier with them).
