### ISSUE TITLE
blockdrops bug/request

### ISSUE THREAD

**Issue by KhaozFrost** [RedNesto/BoxOUtils#3]
would it be possible to only allow natural ores to be considered rather then everyore (the issue im seeing is that a player could silktouch a ore and just constantly mine it over and over

**Comment by RedNesto** [comment]
As far as I know this is impossible without marking every blocks not placed naturally, but I do not see it as a good solution.

However I can add a new requirement to process the ore drops only if the item used does not have silktouch, do you think it will be enough to fix your issue?

**Comment by KhaozFrost** [comment]
yeah that could possibly work.

**Comment by RedNesto** [comment]
The next version will have an `enchantments` requirement, I think this will be enough to solve your issue.

If you need help with anything you can join my discord server.
